### ISSUE TITLE
Combine don't let the perfect defeat the good + learn constantly by embracing failure

### ISSUE THREAD

**Issue by bonniegee** [RockefellerArchiveCenter/dteamValues#10]
These two seem pretty similar to me, particularly the "Focus on creating a workable solution that can be tested and improved" and "Making small, iterative changes allows us to test the outcomes of those changes, and then revise our approach accordingly" parts.

**Comment by helrond** [comment]
:+1: from me for giving this a shot.

**Comment by p-galligan** [comment]
I agree. Personally, I think the first sentence could go. Focus on creating a a workable solution seems obvious.

**Comment by helrond** [comment]
@bonniegee want to give this a shot and create a pull request?
