### ISSUE TITLE
move last sentence of "Focus on the user." to "Practice positive, solution-centered communication."

### ISSUE THREAD

**Issue by helrond** [RockefellerArchiveCenter/dteamValues#13]
I'm wondering if 

> Provide the resources, training, and support necessary for users to feel empowered to use and troubleshoot our systems.

would more appropriately fit under communication? The idea of user-centric focus seems more general and somehow different? Thoughts?

**Comment by bonniegee** [comment]
I see what you're saying. This sentence had been tacked on there from an "Empower users" value that I had added. I would like our user-centric focus to include empowering users and not having them rely on us to do things--but maybe that could be phrased a different way?

**Comment by helrond** [comment]
Maybe we need a better title than "Focus on the user"?

Like "Engage and empower users"?

**Comment by p-galligan** [comment]
I like engage and empower users

**Comment by helrond** [comment]
Hehe, @pjg250 was too quick on the draw!

**Comment by helrond** [comment]
see 0ffeefb5b50d8e7a7fc4eede4c00a63099448fa3
