### ISSUE TITLE
Revise language in "build networks not silos"

### ISSUE THREAD

**Issue by helrond** [RockefellerArchiveCenter/dteamValues#16]
There's some repetition and unnecessary language here that could be streamlined and polished a bit.

**Comment by p-galligan** [comment]
Took a stab at this in networks_cleanup.

**Comment by helrond** [comment]
I would like to keep the part about collaboration in there.

Also, you need to pull master first, before creating a branch. If you want to level up your game you can do `git rebase master` in your branch, which will try to move your branch into alignment with `master`
