### ISSUE TITLE
Add readme

### ISSUE THREAD

**Issue by helrond** [RockefellerArchiveCenter/dteamValues#2]
This should be a file written in Markdown which explains the purpose and scope of the repository content. It's possible we will need to add some disclaimers here too.

**Comment by p-galligan** [comment]
I've never really used Markdown, so I'm not really sure about a good tool for this.

**Comment by helrond** [comment]
This is a good place to start: https://help.github.com/articles/markdown-basics/

**Comment by helrond** [comment]
I'll add an introduction in the document instead.
