### ISSUE TITLE
Define users more clearly?

### ISSUE THREAD

**Issue by helrond** [RockefellerArchiveCenter/dteamValues#27]
@pjg250 and @bonniegee: do you feel like we need to define users more clearly in this document?

**Comment by p-galligan** [comment]
I think we could better define them in the first section. I think that first point reads vaguely as it is right now. It could use some more concrete definitions of "others". Users are: archivists, coworkers, donors, researchers, really anyone. It's hard to break down, but we could say that our users are anyone that interacts with our systems.

**Comment by bonniegee** [comment]
I think the "others" in the first section just means "not us," which I think is okay for that section. Maybe this line
`Provide the resources, training, and support necessary for users to feel empowered to use and troubleshoot our systems.`
could use @pjg250 's definition of our users (anyone that interacts with our systems)?

**Comment by helrond** [comment]
@pjg250 would you be willing to put together a pull request for this that combines your two suggestions?

**Comment by p-galligan** [comment]
@helrond Do you mean that combines this suggest with issue #29 ?

**Comment by helrond** [comment]
@pjg250 no I meant create a new pull request that combines your and @bonniegee's suggestions in this issue thread. Make sense?

**Comment by p-galligan** [comment]
Yep! just wanted to make sure.
