### ISSUE TITLE
remove transparency value

### ISSUE THREAD

**Issue by helrond** [RockefellerArchiveCenter/dteamValues#3]
I feel like this is covered in other values. Consider moving some of this language elsewhere.

**Comment by bonniegee** [comment]
Which other values do you think this is covered in?

**Comment by helrond** [comment]
"Build networks, not silos." covers the systems piece (or could).
"Practice positive, solution-centered communication." does/could cover the people part.

**Comment by bonniegee** [comment]
Fair enough. I think it would make sense to add "Transparency can be achieved by using open software, tools and standards where possible, and by documenting decision-making and prioritization processes" (or a version thereof) to "Build networks, not silos."

**Comment by helrond** [comment]
@bonniegee sounds fine to me. Do you want to take a crack at this? Make the changes in the `remove_transparency` branch and push back up. The pull request should update automatically.
