### ISSUE TITLE
combine "Make and promote continuous and incremental change." and "Learn constantly by embracing failure."

### ISSUE THREAD

**Issue by helrond** [RockefellerArchiveCenter/dteamValues#4]
These seem related to me, and could perhaps be combined.

**Comment by bonniegee** [comment]
I was thinking of possibly removing ""Make and promote continuous and incremental change," so combing those two makes sense to me.

**Comment by helrond** [comment]
Just curious, why did you want to remove that completely?

**Comment by bonniegee** [comment]
It's duplicated elsewhere. Also, I think promoting continuous change is more important to be spelled out than making changes incrementally--and the latter is more spelled out in the description.

**Comment by helrond** [comment]
OK, that makes sense to me!
