### ISSUE TITLE
merge Empower Users and Focus on Users

### ISSUE THREAD

**Issue by p-galligan** [RockefellerArchiveCenter/dteamValues#7]
Two sections seems redundant. Merged these together

**Comment by bonniegee** [comment]
Looks good to me!

**Comment by helrond** [comment]
Just pushed a new commit 75687529cf243e59df2cfa3c7c69b210df640065 to tweak language, otherwise I am okay with this.

**Comment by p-galligan** [comment]
I took a look. I'm fine with the change in wording. Want me to create a pull request and merge?

**Comment by helrond** [comment]
:+1:

**Comment by helrond** [comment]
closed with 103003bfce82c961a2f02c3e0c3432878bae0832
