### ISSUE TITLE
Reorder values based (at least roughly) on priority

### ISSUE THREAD

**Issue by helrond** [RockefellerArchiveCenter/dteamValues#8]
This is something that will probably take a bit of conversation, and we should wait until we've got the values a bit more solidified.

**Comment by p-galligan** [comment]
Here's how I see it:
Access
Engage and empower
Networks not silos
Learn by embracing failure
Solution-centered communication
Invest in profession

However, those last 3 are kinda interchangeable in place for me.

**Comment by bonniegee** [comment]
- I would like "engage and empower" to be first
- I agree with "invest in profession" being last

**Comment by helrond** [comment]
this is pretty much the same as @pjg250's. I just flipped the first two:
- Engage and empower
- Access
- Networks not silos
- Learn by embracing failure
- Solution-centered communication
- Invest in profession

My thinking is that user stuff affects all facets of what we do. While access is pretty fundamental as well, there are some things we do on wrt accessioning that have more to do with our internal users.

**Comment by p-galligan** [comment]
I'm down with this.

**Comment by helrond** [comment]
@bonniegee do you have any other comments or is this good enough for now?

**Comment by bonniegee** [comment]
This looks good to me!

**Comment by helrond** [comment]
Will submit a pull request

**Comment by p-galligan** [comment]
Thanks, I was about to check it out

**Comment by pjg250** [comment]
test
